(add-to-list 'load-path (concat my-emacs-lisp-dir (file-name-as-directory "auto-complete")))
(when (abaw-try-to-require 'auto-complete-config)
  (ac-config-default)
  (setq ac-auto-start nil)
  (ac-set-trigger-key "TAB")
  (defun ac-c/c++-hook ()
    (setf ac-sources (append ac-sources '(ac-source-gtags))))
  (add-hook 'c-mode-hook 'ac-c/c++-hook)
  (add-hook 'c++-mode-hook 'ac-c/c++-hook))
