(let ((helper-file (expand-file-name "~/quicklisp/slime-helper.el")))
  (if (file-exists-p helper-file)
      (progn (load helper-file)
	     (setq inferior-lisp-program "sbcl")
	     (setq slime-complete-symbol-function 'slime-fuzzy-complete-symbol))
    (message "%s: not found %s" (buffer-file-name) helper-file)))
