;;(add-to-list 'load-path (concat my-emacs-lisp-dir "slime"))
;; (load (expand-file-name "~/quicklisp/slime-helper.el"))
;; (setq inferior-lisp-program "/usr/local/bin/sbcl")
;; (require 'slime)
;; (slime-setup '(slime-fancy))
